### PR TITLE
Use pyproject.toml instead of the ancient setup.py for packaging

### PR DESCRIPTION
**Pull request by wigging**
This replaces the outdated setup.py packaging and uses the modern pyproject.toml approach. The requirements text files are also removed as that functionality can be obtained from the pyproject configuration. All code linting and formatting is now done with ruff instead of flake8 and black. Tests related to zambeze have been removed since that project is being re-evaluated. Adjustments to the GitHub Actions workflows have also been made to accommodate the changes in this pull request.

### CODE REVIEW

**Comment by renan-souza** [comment]
@wigging Since this changes the installation workflow, please check the Release Publication workflow: https://github.com/ORNL/flowcept/blob/main/.github/workflows/create-release-n-publish.yml

**Comment by wigging** [comment]
I oppose doing automated releases for such a small project. I also don't think this project should be on PyPI until it has been thoroughly tested and documented. Someone else is welcome to update the release workflow but I suggest removing it completely from the project.

**Comment by renan-souza** [comment]
We'll keep the automated releases. I can work on the workflow. Thanks.

**Comment by wigging** [comment]
This is ready for review. Notice that the ruff linter/formatter checks for docstrings; therefore, I had to add docstrings to almost every file to appease the linter checks. Most of the docstrings I added aren't very useful and act as placeholders for now. More useful docstrings should be added in a future pull request.

**Comment by renan-souza** [comment]
@wigging Can you please show me a few popular repositories that follow the <repo-name>/src/<package name> structure? Some of the references I use (see below) follow the current strategy, i.e., <repo-name>/<package name>.
Unless strongly recommended by best practices, I would like to maintain the current practice in Flowcept.

References:
- Airflow: https://github.com/apache/airflow
- PyTorch: https://github.com/pytorch/pytorch
- MLFlow: https://github.com/mlflow/mlflow
- PySpark: https://github.com/apache/spark/tree/master/python
- Numpy: https://github.com/numpy/numpy
- https://github.com/pandas-dev/pandas

**Comment by renan-souza** [comment]
Also, please note that I am still trying to adhere to the Contributing guidelines, regardless the size of the project: https://github.com/ORNL/flowcept/blob/main/CONTRIBUTING.md

In this case, this PR should go be to the dev branch before going to the main branch.

**Comment by wigging** [comment]
Popular packages that use the src layout:
- requests https://github.com/psf/requests
- flask https://github.com/pallets/flask
- matplotlib https://github.com/matplotlib/matplotlib
- bokeh https://github.com/bokeh/bokeh
- pytest https://github.com/pytest-dev/pytest
- black https://github.com/psf/black
- pygame https://github.com/pygame/pygame
- flake8 https://github.com/PyCQA/flake8
- pendulum https://github.com/sdispater/pendulum
- openscm https://github.com/openscm/openscm-runner
- awkward https://github.com/scikit-hep/awkward

Reasons to use the src layout are [here](https://www.pyopensci.org/python-package-guide/package-structure-code/python-package-structure.html
) and [here](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/
).

**Comment by renan-souza** [comment]
Ok, thanks. We can follow the src layout then.

> Popular packages that use the src layout:
> 
> * requests https://github.com/psf/requests
> * flask https://github.com/pallets/flask
> * matplotlib https://github.com/matplotlib/matplotlib
> * bokeh https://github.com/bokeh/bokeh
> * pytest https://github.com/pytest-dev/pytest
> * black https://github.com/psf/black
> * pygame https://github.com/pygame/pygame
> * flake8 https://github.com/PyCQA/flake8
> * pendulum https://github.com/sdispater/pendulum
> * openscm https://github.com/openscm/openscm-runner
> * awkward https://github.com/scikit-hep/awkward
> 
> Reasons to use the src layout are [here](https://www.pyopensci.org/python-package-guide/package-structure-code/python-package-structure.html) and [here](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/).

**Comment by wigging** [comment]
Why are there a bunch of conflicts to resolve? This was ready to merge without any conflicts when I pushed up the last commit.

**Comment by renan-souza** [comment]
I am also working on the code. There were errors that I had to fix (in the original codebase), making this branch a few commits outdated from the dev branch. These are fixed now and I don't plan to do any new push to the code before we merge this PR.  See this PR: https://github.com/ORNL/flowcept/pull/150

If you decide to do resolve the conflicts in this PR 148, you can ignore PR 150.

**Comment by wigging** [comment]
Looks like you switched the merge branch from main to dev. That is what caused the merge conflicts. I created this branch from main, not dev. There's no reason to use a dev workflow for this project. It just creates more work and headaches for such a small project with one contributor. This will take some time to fix.

**Comment by wigging** [comment]
Changing the pull request from main to dev has really screwed this branch and I can't resolve the conflicts. At this point I'm just going to start over. I'll create a new branch from dev, redo everything I did in this branch, then do another pull request. Actually, I'll do several small pull requests to minimize any merge conflicts that might happen.

**Comment by wigging** [comment]
Keep this open as a draft so I can know which files caused the merge conflicts. I'll close once the other pull request is done.

**Comment by wigging** [comment]
Keep this open until I get all the linter/formatter warnings fixed.

**Comment by wigging** [comment]
Closing this because these changes were done in another pull request to fix the merge conflicts.

**Comment by wigging** [comment]
Deleted. Is automatic branch deletion for pull requests not set up for this repository?

**Pull request closed without merging**
